Wait for heed db closing (#622)
Unit test `test_multiple_resume()` contains a loop where each iteration
internally opens and closes a heed DB that is used for simulating a
global dedup table. If the DB is not fully closed before any call to
open it again, an error is returned leading this unit test to fail:

```
thread 'tests::test_multiple_resume' panicked at data/tests/test_session_resume.rs:140:18:
called `Result::unwrap()` on an `Err` value: CasClientError(Other("Error opening db at \"/var/folders/kg/7q73ww8s3llgyl61c9z_j5g40000gn/T/.tmp09NYmC/xet/xorbs/global_dedup_lookup.db\": database is in a closing phase, you can't open it at the same time"))
```

This PR actually waits for the DB to close in the simulation client's
Drop function.